ALTER TABLE sources ADD COLUMN IF NOT EXISTS is_archived BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE applications ADD COLUMN IF NOT EXISTS source_id TEXT REFERENCES sources(id) ON DELETE SET NULL;
